// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace arma;
using namespace Rcpp;

// mbmC
mat mbmC(const mat& chain, double b);
RcppExport SEXP mcmcse_mbmC(SEXP chainSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< mat >::type chain(chainSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    __result = Rcpp::wrap(mbmC(chain, b));
    return __result;
END_RCPP
}
// msveC
mat msveC(const mat& chain, double b, String method);
RcppExport SEXP mcmcse_msveC(SEXP chainSEXP, SEXP bSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< mat >::type chain(chainSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    __result = Rcpp::wrap(msveC(chain, b, method));
    return __result;
END_RCPP
}

