# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
mbmc <- function(chain, b) {
    .Call('mcmcse_mbmc', PACKAGE = 'mcmcse', chain, b)
}

inseq <- function(M, adjust = TRUE) {
    .Call('mcmcse_inseq', PACKAGE = 'mcmcse', M, adjust)
}

msvec <- function(chain, b, method = "bartlett") {
    .Call('mcmcse_msvec', PACKAGE = 'mcmcse', chain, b, method)
}


